#!/usr/bin/env python3
"""Count asks on the live network honestly — and say why each one is or is not
evidence that an outside agent arrived.

The question this answers is the one the owner put at the core of the work: are
there more asks from agents that are not us, this hour, than last hour? The trap is
that the store is trivially full of rows that look like asks. Measured 2026-09-19:
483 rows, of which 449 are broadcasts of our own; the surface a caller gets by
default is already filtered to type='ask', and 16 of those 34 are literal strings
like 'nano_3test' and 'nano_test1', which the server accepted because
createAsk checks only that the asker STARTS WITH 'nano_'.

So this counts in four tiers, and the top tier is the only one that may be called an
outside ask:

  outside_confirmed  asker recorded as a real outside agent in bridge.db (the only
                     tier that may ever be published as an outside ask).
  addressed_unknown  asker is a valid Nano address that is NOT our opener, is NOT a
                     known synthetic, and is NOT the onramp probe key I generated
                     myself today. An address we cannot attribute to a named agent
                     is a lead, not adoption.
  synthetic          'nano_3test', 'nano_test1', 'nano_3testpost' ... accepted by the
                     server, generated by nobody.
  ours               our own opener account.

Usage:  python3 ask_census.py [--json]
"""
import argparse
import json
import os
import re
import sqlite3
import subprocess
import sys
import urllib.request

BASE = "https://getunstuck.space/unstuck/api/asks?type=all"
OPENER = "nano_1434j1n4sin4cefs5njibag4tsmo596fmg3s6bdogtod3ndmdfez5yuebrh9"
BRIDGE_DB = os.path.expanduser("~/unstuck/opener/bridge.db")
ALPHA = set("13456789abcdefghijkmnopqrstuwxyz")

# A name that marks an identity WE created (an onramp/probe/test agent, a forum we registered, a swarm
# identity) is never an outside counterparty, however real its row in bridge.db. bridge.py's `network()`
# already excludes these; this module did not, so the same three identities ("Unstuck onramp agent 2",
# "Unstuck onramp agent (L68 probe)", "tantive.space forum") counted 4 asks as outside adoption.
# Applied here for the same reason it is applied there: it can only make the number SMALLER, which is
# the honest direction. Kept byte-identical to bridge.py's hint so the two paths cannot drift.
_SELF_HINT = re.compile(r"\b(unstuck|onramp|probe|l68|test|self|forum|nanoswarm)\b", re.I)


def structurally_valid(a):
    return isinstance(a, str) and len(a) == 65 and a.startswith("nano_") and all(c in ALPHA for c in a[5:])


def checksum_valid(a):
    """The independent keygen's own verdict — not the server's, which only prefix-checks."""
    try:
        r = subprocess.run(["python3", os.path.join(os.path.dirname(os.path.abspath(__file__)),
                                                    "nano-keygen.py"), "--check", a],
                           capture_output=True, text=True, timeout=20)
        return bool(json.loads(r.stdout).get("valid"))
    except Exception:
        return False


_VALID_CACHE = {}


def valid_cache(a):
    if a not in _VALID_CACHE:
        _VALID_CACHE[a] = checksum_valid(a)
    return _VALID_CACHE[a]


def outside_accounts():
    """Addresses of agents recorded in the bridge as real outside agents.

    Excludes any agent whose recorded NAME marks an identity we created (_SELF_HINT) — an onramp/probe/
    test agent or a forum we registered is us, not an outside counterparty, however real its row. This is
    the same exclusion bridge.py's `network()` applies, so the two honesty paths agree.
    """
    if not os.path.exists(BRIDGE_DB):
        return set()
    try:
        con = sqlite3.connect(f"file:{BRIDGE_DB}?mode=ro", uri=True)
        rows = con.execute("SELECT account, agent FROM agents WHERE account IS NOT NULL AND account != ''").fetchall()
        con.close()
        return {acct for acct, agent in rows if not _SELF_HINT.search(agent or "")}
    except Exception:
        return set()


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--json", action="store_true")
    ap.add_argument("--probe-keys", default=os.path.join(os.path.dirname(os.path.abspath(__file__)), "probe-keys.txt"),
                    help="file of addresses I generated myself as probes, one per line")
    a = ap.parse_args()

    asks = json.loads(urllib.request.urlopen(BASE, timeout=25).read())["asks"]
    # `confirmed` is the set of accounts recorded in bridge.db for real outside agents; `probe` the
    # addresses I generated myself while testing. The first version named the first one `mine`, which
    # shadowed the module-level helper of the same name: the script then classified seven probe rows
    # as 'addressed_unknown' where the imported module classified them 'synthetic' — same function,
    # two answers, depending on how it was called.
    confirmed = outside_accounts()
    probe = set()
    if os.path.exists(a.probe_keys):
        probe = {l.strip() for l in open(a.probe_keys) if l.strip()}

    tiers = {"outside_confirmed": [], "addressed_unknown": [], "synthetic": [], "ours": []}
    for x in asks:
        asker = x["asker"]
        # The `--check` verdict is memoised: one subprocess per DISTINCT address, not per row.
        # Measured 2026-09-19: without this the census spawned one python3 per row over 490 rows.
        if asker == OPENER:
            tiers["ours"].append(x["id"])
        elif asker in confirmed:
            tiers["outside_confirmed"].append(x["id"])
        elif structurally_valid(asker) and valid_cache(asker) and asker not in probe:
            tiers["addressed_unknown"].append(x["id"])
        else:
            tiers["synthetic"].append(x["id"])

    out = {
        "total_rows": len(asks),
        "tiers": {k: len(v) for k, v in tiers.items()},
        "outside_confirmed_ids": tiers["outside_confirmed"],
        "addressed_unknown_ids": tiers["addressed_unknown"],
        "publishable_as_outside_asks": len(tiers["outside_confirmed"]),
        "note": "Addressed-but-unattributed asks are leads, not adoption. Only an asker "
                "recorded as a real outside agent counts.",
    }
    if a.json:
        print(json.dumps(out, indent=1))
    else:
        print(f"{out['total_rows']} rows on the network "
              f"({tiers and ''})")
        for k in ("outside_confirmed", "addressed_unknown", "synthetic", "ours"):
            print(f"  {k:<18} {len(tiers[k]):>4}  {tiers[k][:8] if tiers[k] else ''}")
        print(f"publishable as outside asks: {out['publishable_as_outside_asks']}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
