#!/usr/bin/env python3
"""
nano-receive.py — let an agent that HOLDS its own seed pocket (receive) its Nano.

This is the receive companion to nano-keygen.py / the keygen one-liner, and closes
the measured gap that keeps every converted agent at `swapped`: an outside agent can
GET a Nano address with one python3 command (keygen), but the only way to *pocket* a
starter was a node script with the nanocurrency dependency. Most agents run python3
and have nothing installed. This tool is pure standard library (hashlib, os, json),
needs no pip, no npm, nothing but the public no-node RPC, and runs on the agent's OWN
machine with the agent's OWN seed — the network never sees the seed.

Usage (agent runs it with its own seed, its own money):
    python3 nano-receive.py --seed <64hex>                 # receive all pending into index 0
    python3 nano-receive.py --seed <64hex> --index 3       # child account
    python3 nano-receive.py --seed <64hex> --check         # show account, opened, balance
    python3 nano-receive.py --seed <64hex> --pending       # list pending sends only

The seed is the AGENT's key (generated by nano-keygen.py / the on-ramp). This tool
never spends treasury money; it only ever pockets sends already addressed to the
seed's account. The receiver of a send is the account's owner; completing the receive
is the agent holding its own key, not the network.

Env:
    NO_NODE_API   (optional) no-node account_info/work/process service (default https://pursekeeper.dev)
    NANO_REP      (optional) representative for an open block (default: a public Nano rep)
"""

import hashlib
import json
import os
import sys
import urllib.request

# ---------------------------------------------------------------------------
# Nano ed25519 (Blake2b-512) — the same math as nano-keygen.py, extended with
# RFC8032 signing so we can build and sign a state block.
# ---------------------------------------------------------------------------

b = 256
q = 2 ** 255 - 19
l = 2 ** 252 + 27742317777372353535851937790883648493
d = -121665 * pow(121666, q - 2, q)
I = pow(2, (q - 1) // 4, q)


def _xrecover(y):
    xx = (y * y - 1) * pow(d * y * y + 1, q - 2, q)
    x = pow(xx, (q + 3) // 8, q)
    if (x * x - xx) % q != 0:
        x = x * I % q
    if x % 2 != 0:
        x = q - x
    return x


_By = 4 * pow(5, q - 2, q)
_Bx = _xrecover(_By)
_B = [_Bx % q, _By % q]


def H(m):
    """Blake2b-512. Nano's ed25519 uses this where RFC8032 uses SHA-512."""
    return hashlib.blake2b(m, digest_size=64).digest()


def _edwards(P, Q):
    x1, y1 = P
    x2, y2 = Q
    x3 = (x1 * y2 + x2 * y1) * pow(1 + d * x1 * x2 * y1 * y2, q - 2, q) % q
    y3 = (y1 * y2 + x1 * x2) * pow(1 - d * x1 * x2 * y1 * y2, q - 2, q) % q
    return [x3, y3]


def _scalarmult(P, e):
    if e == 0:
        return [0, 1]
    Q = _scalarmult(P, e // 2)
    Q = _edwards(Q, Q)
    if e & 1:
        Q = _edwards(Q, P)
    return Q


def _encodepoint(P):
    x, y = P
    bits = [(y >> i) & 1 for i in range(b - 1)] + [x & 1]
    return bytes(sum([bits[i * 8 + j] << j for j in range(8)]) for i in range(b // 8))


def _bit(h, i):
    return (h[i // 8] >> (i % 8)) & 1


def public_key_from_private(private_key):
    h = H(private_key)
    a = 2 ** (b - 2) + sum(2 ** i * _bit(h, i) for i in range(3, b - 2))
    return _encodepoint(_scalarmult(_B, a))


def private_key_from_seed(seed, index=0):
    return hashlib.blake2b(seed + index.to_bytes(4, "big"), digest_size=32).digest()


def _decode_point(public_key):
    y = sum(2 ** i * _bit(public_key, i) for i in range(0, b - 1))
    x = _xrecover(y)
    if x & 1 != _bit(public_key, b - 1):
        x = q - x
    return [x, y]


def sign(secret_key, message):
    """Ed25519 (Blake2b-512) signature over `message` (the 32-byte block hash).
    Matches the tweetnacl/Nano variant that nanocurrency uses: nonce and hram are
    the full 64-byte Blake2b-512 digests reduced mod L as little-endian integers."""
    h = H(secret_key)
    a = 2 ** (b - 2) + sum(2 ** i * _bit(h, i) for i in range(3, b - 2))
    prefix = h[b // 8:]
    # r = full 64-byte H(prefix || M), little-endian, reduced mod L
    r = int.from_bytes(H(prefix + message), "little") % l
    R = _encodepoint(_scalarmult(_B, r))
    A = public_key_from_private(secret_key)
    # k = full 64-byte H(R || A || M), little-endian, reduced mod L
    k = int.from_bytes(H(R + A + message), "little") % l
    S = (r + k * a) % l
    return R + S.to_bytes(b // 8, "big")


# ---------------------------------------------------------------------------
# Nano address + block encoding
# ---------------------------------------------------------------------------

ALPHABET = "13456789abcdefghijkmnopqrstuwxyz"


def _base32_encode(data):
    bits = "".join(f"{x:08b}" for x in data)
    bits = "0" * ((5 - len(bits) % 5) % 5) + bits
    return "".join(ALPHABET[int(bits[i:i + 5], 2)] for i in range(0, len(bits), 5))


def _base32_decode(text):
    bits = "".join(f"{ALPHABET.index(c):05b}" for c in text)
    bits = bits[4:]
    return bytes(int(bits[i:i + 8], 2) for i in range(0, len(bits), 8))


def address_from_public_key(public_key, prefix="nano_"):
    checksum = hashlib.blake2b(public_key, digest_size=5).digest()[::-1]
    return prefix + _base32_encode(public_key + checksum)


def public_key_from_address(address):
    body = address[len("nano_"):] if address.startswith("nano_") else address
    raw = _base32_decode(body)
    return raw[:32]


def account_from_seed(seed, index=0):
    private_key = private_key_from_seed(seed, index)
    public_key = public_key_from_private(private_key)
    return {
        "seed": seed.hex().upper(),
        "index": index,
        "private_key": private_key.hex().upper(),
        "public_key": public_key.hex().upper(),
        "address": address_from_public_key(public_key),
    }


def block_hash(account_pub, previous, representative_pub, balance_raw, link):
    """Nano state-block hash: blake2b-32( type_header[32] || account[32] ||
    previous[32] || representative[32] || balance[16 BE] || link[32] ) = 176 bytes.
    type_header is 31 zero bytes then 0x06 (the Nano state-block type)."""
    header = bytearray(32)
    header[31] = 6  # state block type
    buf = bytes(header) + account_pub + bytes.fromhex(previous) + representative_pub \
        + int(balance_raw).to_bytes(16, "big") + bytes.fromhex(link)
    return hashlib.blake2b(buf, digest_size=32).digest()


# ---------------------------------------------------------------------------
# No-node RPC (default pursekeeper.dev; no key needed for reads/work/process)
# ---------------------------------------------------------------------------

def _post(path, payload, ok_status=(200, 201)):
    url = NO_NODE_API + path
    req = urllib.request.Request(
        url,
        data=json.dumps(payload).encode() if payload is not None else None,
        headers={"Content-Type": "application/json"} if payload is not None else {},
        method="POST" if payload is not None else "GET",
    )
    with urllib.request.urlopen(req, timeout=30) as r:
        if r.status not in ok_status:
            raise RuntimeError(f"{path} HTTP {r.status}: {r.read()[:200]!r}")
        return json.loads(r.read())


def account_info(account):
    url = NO_NODE_API + "/v1/account_info?account=" + account
    with urllib.request.urlopen(url, timeout=30) as r:
        return json.loads(r.read())


def receivable(account):
    url = NO_NODE_API + "/v1/receivable?account=" + account + "&min_raw=1"
    with urllib.request.urlopen(url, timeout=30) as r:
        return json.loads(r.read())


def work_for(hash_hex):
    try:
        r = _post("/v1/work", {"hash": hash_hex})
        if r.get("work"):
            return r["work"]
    except Exception as e:
        sys.stderr.write(f"work service failed ({e}); computing locally ~20-30s...\n")
    return compute_work_local(hash_hex)


def compute_work_local(hash_hex):
    """Minimal CPU PoW: find a 64-hex value whose blake2b-32 (8-byte prefix)
    meets difficulty fffffff800000000. Reference only — most agents use /v1/work."""
    import struct
    target_hi = 0xfffffff8
    target = (target_hi << 32)
    h = bytes.fromhex(hash_hex)
    nonce = 0
    while True:
        buf = nonce.to_bytes(8, "little") + h
        d = hashlib.blake2b(buf, digest_size=8).digest()
        val = int.from_bytes(d[:4], "big")
        if val < target_hi:
            return nonce.to_bytes(8, "little").hex()
        nonce += 1


def process_block(block):
    r = _post("/v1/process", {"block": block})
    if r.get("error") or not r.get("hash"):
        raise RuntimeError("process: " + json.dumps(r))
    return r["hash"]


def build_and_submit(seed, index, opened, previous, representative, balance, amount_raw, link, rep_pub):
    sk = private_key_from_seed(seed, index)
    pk = public_key_from_private(sk)
    account = address_from_public_key(pk)
    new_balance = balance + amount_raw
    if opened:
        work_hash = previous
        subtype = "receive"
    else:
        work_hash = pk.hex().lower()
        subtype = "open"
    w = work_for(work_hash)
    balance_hex = str(new_balance)
    blk_hash = block_hash(pk, previous, rep_pub, balance_hex, link)
    sig = sign(sk, blk_hash)
    block = {
        "type": "state",
        "account": account,
        "previous": previous,
        "representative": representative,
        "balance": balance_hex,
        "link": link,
        "work": w,
        "signature": sig.hex().upper(),
        "subtype": subtype,
    }
    new_hash = process_block(block)
    return new_hash, block, subtype


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------

NO_NODE_API = (os.environ.get("NO_NODE_API") or "https://pursekeeper.dev").rstrip("/")
DEFAULT_REP = os.environ.get("NANO_REP") or (
    "nano_3arg3asgtigae3xckabaaewkx3bzsh7nwz7jkmjos79ihyaxwphhm6qgjps4"
)


def check(seed, index):
    acct = account_from_seed(seed, index)
    info = account_info(acct["address"])
    if info.get("found") is False or info.get("error"):
        print(json.dumps({"account": acct["address"], "opened": False, "balance_raw": "0",
                          "message": "account not opened yet (a starter is receivable until received)"}, indent=2))
        return
    print(json.dumps({"account": acct["address"], "opened": True,
                      "balance_raw": info.get("balance") or info.get("balance_raw"),
                      "balance_nano": info.get("balance_nano") or info.get("balance_raw"),
                      "representative": info.get("representative")}, indent=2))


def pending(seed, index):
    acct = account_from_seed(seed, index)
    r = receivable(acct["address"])
    print(json.dumps({"account": acct["address"], "count": r.get("count", 0),
                      "blocks": r.get("blocks", [])}, indent=2))


def receive(seed, index):
    acct = account_from_seed(seed, index)
    account = acct["address"]
    pend = receivable(account)
    blocks = pend.get("blocks", [])
    if not blocks:
        print(json.dumps({"account": account, "action": "receive", "received": 0,
                          "message": "nothing receivable"}, indent=2))
        return 0
    rep_pub = public_key_from_address(DEFAULT_REP)
    info = account_info(account)
    opened = not (info.get("found") is False or info.get("error"))
    previous = info["frontier"] if opened else "0" * 64
    balance = int(info.get("balance") or 0)
    representative = info.get("representative") or DEFAULT_REP
    results = []
    for blk in blocks:
        link = blk.get("hash")
        amount_raw = int(blk.get("amount_raw") or blk.get("amount") or 0)
        new_hash, block, subtype = build_and_submit(seed, index, opened, previous,
                                                    representative, balance, amount_raw, link, rep_pub)
        results.append({"action": subtype, "hash": new_hash, "amount_raw": str(amount_raw)})
        opened = True
        previous = new_hash
        balance += amount_raw
    print(json.dumps({"account": account, "action": "receive", "received": len(results),
                      "blocks": results}, indent=2))
    return 0


def main(argv):
    args = list(argv)
    index = 0
    seed = None
    mode = "receive"
    while args:
        a = args.pop(0)
        if a == "--seed":
            seed = bytes.fromhex(args.pop(0))
        elif a == "--index":
            index = int(args.pop(0))
        elif a == "--check":
            mode = "check"
        elif a == "--pending":
            mode = "pending"
        elif a in ("-h", "--help"):
            print(__doc__.strip())
            return 0
        else:
            print(f"unknown argument: {a}", file=sys.stderr)
            return 2
    if seed is None:
        print("set --seed <64hex> — the agent's own seed (from nano-keygen.py / the on-ramp)", file=sys.stderr)
        return 2
    if len(seed) != 32:
        print("seed must be 32 bytes (64 hex chars)", file=sys.stderr)
        return 2
    if mode == "check":
        return check(seed, index) or 0
    if mode == "pending":
        return pending(seed, index) or 0
    return receive(seed, index)


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
