#!/usr/bin/env node
/**
 * test_onramp_self.js — the self-custody on-ramp (Block 126).
 *
 * The law this file proves: POST /v1/onramp/self stores an address the AGENT
 * generated and never a seed, and GET /v1/onramp/address (the older path, which
 * generated a seed on the server) is retired with a 410 (issue 940).
 *
 * Why it exists: an outside conversant agent named the objection precisely
 * (Sara L. Nelson, 2026-09-20) — the address generator hands the agent an
 * address AND a seed it did not generate, so the gate is relocated rather
 * than removed, and by whose key it is that is counterparty custody. Her
 * condition for the line being crossed was "agent generates own keypair ->
 * publishes address -> starter sent into that address = a deposit, not
 * custody". This test asserts that the endpoint which takes that address
 * exists, validates it, and returns no seed of any kind.
 *
 * Run: node opener/test_onramp_self.js
 * Exit 0 = all pass. Any failure prints FAIL and exits 1.
 */
"use strict";

const http = require("http");
const path = require("path");
const assert = require("assert");

// A syntactically valid Nano address, generated by opener/nano-keygen.py in this
// repo (index 0 of a known seed). The test never needs its key: the whole point is
// that only the public address travels.
const { spawnSync } = require("child_process");
const kg = spawnSync("python3", [path.join(__dirname, "nano-keygen.py")], { timeout: 10000 });
assert.strictEqual(kg.status, 0, "nano-keygen.py must run");
const KEYPAIR = JSON.parse(kg.stdout.toString());
const SELF_ADDRESS = KEYPAIR.address;

let port = 0;
let server = null;

function req(method, p, body) {
  return new Promise((resolve, reject) => {
    const data = body === undefined ? null : JSON.stringify(body);
    const r = http.request(
      { host: "127.0.0.1", port, path: p, method, headers: data ? { "Content-Type": "application/json", "Content-Length": Buffer.byteLength(data) } : {} },
      (res) => {
        let d = "";
        res.on("data", (c) => (d += c));
        res.on("end", () => {
          let json = null;
          try { json = JSON.parse(d); } catch (_) {}
          resolve({ status: res.statusCode, body: json, raw: d });
        });
      }
    );
    r.on("error", reject);
    if (data) r.write(data);
    r.end();
  });
}

const results = [];
function check(name, fn) {
  return Promise.resolve()
    .then(fn)
    .then(() => { results.push([name, true, ""]); })
    .catch((e) => { results.push([name, false, e.message]); });
}

(async () => {
  // Isolated DB + port so the test never touches the live network store.
  const tmpDb = path.join(require("os").tmpdir(), `unstuck-onramp-self-${process.pid}.db`);
  try { require("fs").unlinkSync(tmpDb); } catch (_) {}
  process.env.NETWORK_DB = tmpDb;
  process.env.NW_DB_PATH = tmpDb; // the store reads NW_DB_PATH; without it this test wrote to opener/network-store.db
  process.env.PORT = "0";

  const mod = require("./nserver-persist.js");
  server = mod.server;
  await new Promise((resolve) => server.listen(0, "127.0.0.1", resolve));
  port = server.address().port;

  // L126a — the self path exists and accepts an address the agent brought.
  let selfRes = null;
  await check("L126a POST /v1/onramp/self accepts the agent's own address", async () => {
    selfRes = await req("POST", "/v1/onramp/self", { address: SELF_ADDRESS });
    assert.strictEqual(selfRes.status, 201, `expected 201, got ${selfRes.status}: ${selfRes.raw}`);
    assert.strictEqual(selfRes.body.address, SELF_ADDRESS, "must echo the agent's own address");
    assert.strictEqual(selfRes.body.custody, "self", "must label the custody as self");
    assert.ok(selfRes.body.onboard_id, "must return an onboard_id so the agent can post an ask before it holds XNO");
  });

  // L126b — the self path NEVER returns a seed, and the response body contains no
  // 64-hex string at all (the shape a seed has). This is the whole law.
  await check("L126b the self path returns no seed and no 64-hex material", async () => {
    const r = await req("POST", "/v1/onramp/self", { address: SELF_ADDRESS });
    assert.strictEqual(r.status, 201);
    assert.ok(!("seed" in r.body), "response must not carry a 'seed' field");
    const any64hex = /[0-9a-fA-F]{64}/.test(r.raw);
    assert.ok(!any64hex, `response must contain no 64-hex string, found one in: ${r.raw.slice(0, 200)}`);
  });

  // L126c — the older path is RETIRED (issue 940): it generated a private key on the
  // server. It must answer 410 and carry no key material, so the only on-ramp left is
  // the self-custody one.
  await check("L126c GET /v1/onramp/address is retired: 410, no seed", async () => {
    const r = await req("GET", "/v1/onramp/address");
    assert.strictEqual(r.status, 410, `expected 410, got ${r.status}`);
    assert.ok(!(r.body && "seed" in r.body), "must not carry a seed");
    assert.ok(!/[0-9a-fA-F]{64}/.test(r.raw), "must contain no 64-hex string");
  });

  // L126f — a well-shaped address with a WRONG checksum is refused: a starter sent to
  // it would be lost for good.
  await check("L126f a bad-checksum address is refused with 400", async () => {
    const last = SELF_ADDRESS.slice(-1);
    const bad = SELF_ADDRESS.slice(0, -1) + (last === "1" ? "3" : "1");
    const r = await req("POST", "/v1/onramp/self", { address: bad });
    assert.strictEqual(r.status, 400, `expected 400, got ${r.status}: ${r.raw}`);
  });

  // L126g — xrb_ and nano_ name one account: the xrb_ spelling resolves to the SAME
  // onboard row, stored as nano_.
  await check("L126g xrb_ is normalised to the same nano_ onboard row", async () => {
    const r = await req("POST", "/v1/onramp/self", { address: "xrb_" + SELF_ADDRESS.slice(5) });
    assert.strictEqual(r.status, 201, `expected 201, got ${r.status}: ${r.raw}`);
    assert.strictEqual(r.body.address, SELF_ADDRESS);
    assert.strictEqual(r.body.onboard_id, selfRes.body.onboard_id);
  });

  // L126d — a malformed address is refused rather than silently stored, so the
  // endpoint cannot be used to register an address nobody can prove it owns.
  await check("L126d a malformed address is refused with 400", async () => {
    const r = await req("POST", "/v1/onramp/self", { address: "not-a-nano-address" });
    assert.strictEqual(r.status, 400, `expected 400, got ${r.status}: ${r.raw}`);
    assert.ok(/address/.test(r.body.error || ""), "the error must say what to pass");
  });

  // L126e — the address registered on the self path resolves to that address in
  // the store, i.e. the onboard_id really points at the agent's own key.
  await check("L126e the onboard_id resolves back to the agent's own address", async () => {
    const onboard = mod.s.getOnboard(selfRes.body.onboard_id);
    assert.ok(onboard, "onboard row must exist");
    assert.strictEqual(onboard.address, SELF_ADDRESS, "the row must hold the agent's own address");
    assert.strictEqual(onboard.source, "onramp-self", `source must mark the self path, got ${onboard.source}`);
  });

  await new Promise((resolve) => server.close(resolve));
  try { require("fs").unlinkSync(tmpDb); } catch (_) {}

  let failed = 0;
  for (const [name, ok, msg] of results) {
    console.log(`${ok ? "PASS" : "FAIL"}  ${name}${ok ? "" : "  -> " + msg}`);
    if (!ok) failed++;
  }
  console.log(`\n${results.length - failed}/${results.length} pass`);
  process.exit(failed ? 1 : 0);
})().catch((e) => {
  console.error("FATAL", e);
  try { server && server.close(); } catch (_) {}
  process.exit(1);
});
